/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_sec_CommandExecution */

#ifndef _Included_jni_sec_CommandExecution
#define _Included_jni_sec_CommandExecution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_sec_CommandExecution
 * Method:    exec
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1sec_CommandExecution_exec
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
